if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }

__d("HostnameRewriter",["ConstUriUtils","Env","URI","isFacebookURI","lowerFacebookDomain"],(function(a,b,c,d,e,f,g){var h=function(a){return String(a).replace(/([.*+?^=!:${}()|[\]\/\\])/g,"\\$1")},i=null,j=null,k=new RegExp("facebook\\.com$"),l=new RegExp("^www\\.(|.*\\.)facebook\\.com$"),m=null,n="facebook.com",o=null,p=new RegExp("fbcdn\\.net$"),q=new RegExp("^www\\."),r=new RegExp("(^|\\.)(facebook\\.com|workplace\\.com)$","i");function s(){i=null;var a="(^|\\.)";m=a+h(n)+"$";j=null}function t(){if(m==null)return null;if(i)return i;i=new RegExp(m,"i");return i}function u(){if(j)return j;j=new RegExp("(^|\\.)("+h(n)+"|facebook\\.com)$","i");return j}function v(a){if(u().test(a)&&n!=null)return a.replace(k,n);else if(o!=null&&a!==null)return a.replace(p,o);return a}function w(a){return l.test(a)?a.replace(q,"web."):a}function x(a){return function(b){b=new(c("URI"))(b);b.setDomain(a(b.getDomain()));return b}}function y(a,b){n=a,o=b,s(),c("isFacebookURI").setRegex(t()),c("URI").registerFilter(x(v)),d("ConstUriUtils").registerDomainFilter(v),c("lowerFacebookDomain").setDomain(n)}function a(a,b){n=a,c("URI").registerFilter(x(w))}function b(){var a=c("Env").hostnameRewriterConfig;if(a==null)return;switch(a.site){case"onion":y(a.inboundName,a.cdnDomainName);break}}function e(){c("isFacebookURI").setRegex(r)}g.registerFacebookOverTorFilters=y;g.registerInternetDotOrgFilters=a;g.maybeRegisterFilters=b;g.treatWorkplaceAsFacebookURI=e}),98);
__d("FBShopAdminBannerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4724021434277505"}),null);
__d("ProfileCometComposerRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4841840292547757"}),null);
__d("XAdsEventsManagerBusinessGKController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/events_manager/business_gk/",{biz_id:{type:"FBID",required:!0},gk_name:{type:"String",required:!0}})}),null);
__d("XAppSettingsAsyncDeleteController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/ajax/settings/apps/delete_app_multi/",{__asyncDialog:{type:"Int"},app_ids:{type:"String"},surface:{type:"Enum",defaultValue:"applications",enumType:1},refresh_page_on_success:{type:"Bool",defaultValue:!1},refresh_page_on_done:{type:"Bool",defaultValue:!1},page_id:{type:"Int"},privacy_mutation_token:{type:"String"}})}),null);
__d("XBCMPCreatorController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/collabsmanager/creator/{?*child_path}/",{child_path:{type:"String"},action:{type:"Enum",enumType:1},aymt_channel:{type:"String"},aymt_signal_type:{type:"Enum",enumType:1},bc_auto_shown_tagged_post_id:{type:"FBIDVector"},auto_shown_insights_view:{type:"String"},campaign_active_tab:{type:"Enum",enumType:1},campaign_agreement_id:{type:"FBID"},deal_id:{type:"FBID"},entry_source:{type:"Enum",enumType:1},page_id:{type:"FBID"},ppt_tab:{type:"Enum",enumType:1},rfp_id:{type:"FBID"},sponsorship_id:{type:"FBID"},use_bcm:{type:"Bool",defaultValue:!1},media_manager_mode:{type:"Enum",enumType:1},privacy_mutation_token:{type:"String"}})}),null);
__d("XBusinessHomeController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/",{personal:{type:"Exists",defaultValue:!1},business_id:{type:"FBID"},migrated_business_name:{type:"String"}})}),null);
__d("XBusinessSendVerificationCodeToPendingEmailController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/send/verification/email/",{persona_id:{type:"Int",required:!0},is_personal_ads_persona:{type:"Bool",defaultValue:!1}})}),null);